### ISSUE TITLE
all function smoothly, but i got 1 problem. password did't update into database, but username,email, and active is update normally. please help me.

### ISSUE THREAD

**Issue by hasif91** [daveismyname/loginregister#10]
![image](https://cloud.githubusercontent.com/assets/19556524/15635547/9a30b5c2-2613-11e6-8c6d-bb0ca4800b66.png)

this is my problem,i think maybe some error in hashed code in index.php or password.php
![image](https://cloud.githubusercontent.com/assets/19556524/15635560/201712f8-2614-11e6-81d9-e969cd406345.png)

 i upload it on server online. anything else work fine, email also work smoothly. Thanks.

**Comment by daveismyname** [comment]
Hi what version of php are you running this on? 

The functions for hashing only work on php 5.3 and up. You really should not be using anything less then 5.5 now the rest are deprecated and no longer supported by php.
