### ISSUE TITLE
How do I remove Email authentication?

### ISSUE THREAD

**Issue by henry7720** [daveismyname/loginregister#13]
The email authentication is unreliable, because it either sends it to your Spam folder, or, it doesn't send at all! Is there a way to remove this feature? What steps would I have to take to do so?

**Comment by orlandovillarreal** [comment]
The email verification works fine. The message being sent to spam or not being sent at all are server-side issues. 
1- Have you checked if you are actually allowed to send mails via PHP? 
2- There can be a lot of reasons of why your messages are arriving to the spam folder. For example, your server's IP could've been flagged by email providers, etc. 

You can solve both of these issues by using SMTP to send your emails through it. There are lots of providers you can chose from, I use Sendgrid,

**Comment by daveismyname** [comment]
this has been answered in #17
