### ISSUE TITLE
How to get the hash password

### ISSUE THREAD

**Issue by tangyi90** [daveismyname/loginregister#16]
I created two hash passwords
![666](https://cloud.githubusercontent.com/assets/14145481/26277033/9cc7e3c6-3db6-11e7-93d3-064473bcb480.jpg)

The second is for the transaction password
How to verify the second password

This is my code, but it can not work
![777](https://cloud.githubusercontent.com/assets/14145481/26277046/d349beb0-3db6-11e7-9a59-dd07370a4cd4.jpg)

**Comment by daveismyname** [comment]
in get_user_hash() make sure you've added PassWordII to the list of columns being selected from the database.
