### ISSUE TITLE
activate.php

### ISSUE THREAD

**Issue by Beninegoita** [daveismyname/loginregister#19]
Add this piece of code at the beginning, otherwise will give an error when accessed directly 👍 
php if ( ! defined( 'ABSPATH' ) ) {
	exit;}

**Comment by pruah** [comment]
would be better to replace the two $_GET lines with the following:

$memberID = isset($_GET['getvar']) ? trim($_GET['x']) : '';
$active = isset($_GET['getvar']) ? trim($_GET['y']) : '';

**Comment by daveismyname** [comment]
yes, the ternary is better, submit a PR and I'll accept it.submit
