### ISSUE TITLE
add user profile data

### ISSUE THREAD

**Issue by ARABICDEV** [daveismyname/loginregister#23]
hi sear
i try to add a php file for user profile but its not working
can you pleas tel me how i can do it
my problem ishere
`<h2>Member only page - Welcome <?php echo $_SESSION['username']; ?></h2			<h2>Member only page - Welcome <?php echo htmlspecialchars($_SESSION['username'], ENT_QUOTES); ?></h2>
`

  			
i need other field from database email and other field sdv
thank you

**Comment by puremilkorwhite** [comment]
You are missing the > in your first </h2
Hope this helps

**Comment by daveismyname** [comment]
thanks, I'll correct the mistake. 

To get other information from the database you can do 

```
$stmt = $db->prepare('SELECT email FROM members WHERE username = :username');
$stmt->execute(array(':username' => $_SESSION['username']));
$row = $stmt->fetch(PDO::FETCH_ASSOC);
```

Then use `$row['email']` to use it.
