### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Xoduz** [daveismyname/loginregister#26]
Hi! In https://daveismyname.blog/login-and-registration-system-with-php (great tutorial, much appreciated!) you mention at the bottom of the page that your tutorial and code can be used as "a starting point to build members based sites", and in your page's footer it says "All code MIT license". However, for the complete code in this loginregister repo, there seems to be no such license attached (although I noticed that some of your other repos do).

Could you pretty please consider adding one, to make it clear whether the code can actually be used as a starting point, as you described? :)

**Comment by daveismyname** [comment]
yes, I've now added a MIT licence.

Thanks so much for your feedback I do appreciate it.
