### ISSUE TITLE
can it support sqlite?

### ISSUE THREAD

**Issue by maplewang** [daveismyname/loginregister#27]
For small system MySQL is heavy.

**Comment by daveismyname** [comment]
in theory yes it can be switched, I haven't used sqlite myself so can't comment how easy/hard that would be.

**Comment by maplewang** [comment]
by changing config.php these line, it works on sqlite;
   $db = new PDO('sqlite:C:\db\UserData.db');
    // Set errormode to exceptions
    $db->setAttribute(PDO::ATTR_ERRMODE, 
                            PDO::ERRMODE_EXCEPTION);
I make sqlite database under c:\db.
Thanks

**Comment by adamf1631** [comment]
Why not just use MongoDB?
