### ISSUE TITLE
Keep Connected feature

### ISSUE THREAD

**Issue by Serveurperso** [daveismyname/loginregister#28]
Missing feature : checkbox with cookies (login+hash) to auto reconnect on private computers:)

**Comment by adamf1631** [comment]
great idea, can you leave a source doc for that?

**Comment by Serveurperso** [comment]
English isn't my first language, so please excuse any mistakes

It's easy as :

When the user is authenticated, if the "auto login" checkbox is enabled, create two cookie, one with username and one with the DB password hash.

When user return on the website, if cookies are correct (same as db), autologin/create session like the standard process...

Any launch of new security process (change password...) re-ask the password and check the database.

On logout, delete the two cookie (and session...)

Pascal

**Comment by Serveurperso** [comment]
https://codereview.stackexchange.com/questions/122130/remember-me-automatic-login

**Comment by Serveurperso** [comment]
https://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website

 488
down vote
accepted
Improved Persistent Login Cookie Best Practice

You could use this strategy described here as best practice (2006) or an updated strategy described here (2015):

    When the user successfully logs in with Remember Me checked, a login cookie is issued in addition to the standard session management cookie.
    The login cookie contains a series identifier and a token. The series and token are unguessable random numbers from a suitably large space. Both are stored together in a database table, the token is hashed (sha256 is fine).
    When a non-logged-in user visits the site and presents a login cookie, the series identifier is looked up in the database.
        If the series identifier is present and the hash of the token matches the hash for that series identifier, the user is considered authenticated. A new token is generated, a new hash for the token is stored over the old record, and a new login cookie is issued to the user (it's okay to re-use the series identifier).
        If the series is present but the token does not match, a theft is assumed. The user receives a strongly worded warning and all of the user's remembered sessions are deleted.
        If the username and series are not present, the login cookie is ignored.

This approach provides defense-in-depth. If someone manages to leak the database table, it does not give an attacker an open door for impersonating users.

**Comment by Serveurperso** [comment]
A paranoid implementation is not needed, KISS is better for this simple script.
