### ISSUE TITLE
problem after upgrade PHP 7.3

### ISSUE THREAD

**Issue by Deubow** [daveismyname/loginregister#29]
Hello,

Your login form doesn't support PHP 7.3.

When I try to upgrade my PHP version from 5.6 to 7.3, It's impossible to login.

**Comment by daveismyname** [comment]
can you be more specific? I've just installed this on a VM running php 7.3 and it works for me.

http://phpstack-260624-811080.cloudwaysapps.com

**Comment by Deubow** [comment]
Did you sucess on log in ? When I log in to the website, I stay on the login page without error message.

The log in function works to PHP 7.1, but with PHP 7.2 or 7.3, Its seems to the log in doesn't retrieve the user session.

When I tried to catch the user session after log in, the variable is empty.

**Comment by daveismyname** [comment]
you can use the link above to test this I can see the session data, this is working on 7.3.

Try it on my version above.

**Comment by zazasco** [comment]
its working am using PHP 7.3 as well.

**Comment by Deubow** [comment]
Ok, thank you. Its probably a problem with my dev.
