### ISSUE TITLE
Gmail not received on successful registration

### ISSUE THREAD

**Issue by Maciej5** [daveismyname/loginregister#31]
Hi Guys, I was testing this login and I was so excited it works until I found that Gmail did not received confirmation email. So I had to manually confirm Yes in MYSQL Database in order to enable login. Can anyone know whats going on and/or fix that issue?

**Comment by zazasco** [comment]
login your gmail account:

- Click on the google apps Icon
- Click Account
- Locate security and click on it
- scroll down and turn off 2-step verification
- scroll down again and turn On Less Secure App Access

after this try signing up again

**Comment by zazasco** [comment]
![acc](https://user-images.githubusercontent.com/25632227/56471342-31a81500-6449-11e9-84c0-a28dcf7f8c53.JPG)
![2step](https://user-images.githubusercontent.com/25632227/56471346-42588b00-6449-11e9-8134-7cf332deb074.JPG)
![access](https://user-images.githubusercontent.com/25632227/56471355-543a2e00-6449-11e9-9d6f-0260240a523e.JPG)

here are the image preview of it in case of any challenges

**Comment by Maciej5** [comment]
Hey Isaiah,

 

Thank you so so much for this answer.

 

The email had finally arrived with like 3-4 hours of delay and with notifications that it might be a spam.

 

I hope your email is going to work.

 

Using this occasion I would like to ask you about emailer.php license, can I use emailer license on my commercial project without any restriction?

 

I ask because I initially though that all the files have one license but I latre discovered that there is a separate license for emailer.

 

Regards.

 

Maciej

 

Sent: Sunday, April 21, 2019 at 3:23 PM

**Comment by daveismyname** [comment]
My files you can do whatever you like with them for the mailer their licence is available https://github.com/PHPMailer/PHPMailer/blob/master/LICENSE

**Comment by Maciej5** [comment]
Hi David,

 

Thank you for your answer.

 

Is there anyone who provides free or paid support in case I want to incorporate this files into my project?

 

Regards

 

Maciej

 

Sent: Sunday, April 21, 2019 at 5:01 PM

**Comment by daveismyname** [comment]
I've just tried this on another server with gmail and mine is not working at all but works find when I use another providers SMTP so I'm thinking the issue is with Gmail.

I recommend to use a SMTP service. I'm using Office365 since I use them for my emails. Mailgun is a popular one too.

I'm happy to provide support, my Slack group is better for general support https://daveismynameblog.slack.com/join/shared_invite/enQtMzA2MjU4NjExNTU4LThlMTVkY2M2ZTE0MmUzZjk1MDY5N2E3MjQ0NTY2ZmQzOGVhZTgyN2M5NzIyMzk5M2ZlN2VjYmRiYjM2MGM4NDg

**Comment by Maciej5** [comment]
Thank you
 

Sent: Thursday, May 09, 2019 at 8:29 PM

**Comment by Maciej5** [comment]
Thank you
 

Sent: Thursday, May 09, 2019 at 8:29 PM
