### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by zazasco** [daveismyname/loginregister#32]
I tried creating a contact page but it's giving me error... I will post my code later here today

**Comment by zazasco** [comment]
<?php 	
    require('includes/config.php');
$page_title = 'Contact Us - Mind Food Publications';
		include_once 'partials/header2.php'; 	?>
		
	
	<?php
	$msg= "";
if(isset($_POST['submit'])){
   
   $name = $_POST['name'];
   $email = $_POST['email'];
   $subject = $_POST['subject'];
   $phone = $_POST['phone'];
   $message = $_POST['message'];
   
   if (!isset($_POST['name'])) $error[] = "Name Required";
    if (!isset($_POST['email'])) $error[] = "Email Required";
    if (!isset($_POST['subject'])) $error[] = "Subject Required";
    if (!isset($_POST['phone'])) $error[] = "Phone required";
    if (!isset($_POST['message'])) $error[] = "Message required";
    /*if(strlen($message) <= 4){
        $error[] = "Message content can't be lesser than 4 characters";
    } */
    
    if(!isset($error)){
        
        
        try{
            $stmt = $db->prepare( 'INSERT INTO contact (name, email, subject, phone, message, status) VALUES(:name, :email, :subject, :phone, :message)');
        $stmt->execute(array(
			    ':name' => $name,
			    ':email' => $email,
			    ':subject' => $subject,
			    ':phone' => $phone,
			    ':message' => $message,
			    
			    ));
			    
			 //send email
			//$to = $_POST['email'];
			//$subject = "Registration Confirmation";
			//$body = "<p>Thank you for registering at Mindfood Publications.</p>
			//<p>To activate your account, please click on this link: <a href='".DIR."activate.php?x=$id&y=$activasion'>".DIR."activate.php?x=$id&y=$activasion</a></p>
			//<p>Regards Site Admin</p>";
  
  
            $to = 'info@mindfoodpubs.com';
			$subject = $_POST['subject'];
            $body='<h1 align=center>Name: '.$_POST['name'].'<br/>Email: '.$_POST['email'].'<br/>Phone: '.$_POST['phone']. '<br/>Message: '.$_POST['message'].'<h1>';
            
            
			$mail = new Mail();
			$mail->setFrom($_POST['emai'], $_POST['name']);
			$mail->addAddress($to);
			$mail->subject($subject);
			$mail->body($body);
			$mail->send();
			
    
    if(!$mail->send()){
        $error[] = "Message sending failed, please try again later";
    } else{
        //redirect to index page
			header('Location: contact.php?action=sent');
			exit;
    }
           
        } catch(PDOException $ex){
            $error[] = $ex->getMessage();
        }
    }
    
    
    
}
?>


<div class="contact">
		<div class="container">
			<h3 class="w3l-titles">Mail Us</h3>
			<div class="col-md-3 col-sm-3 contact-left">
				<div class="address">
					<h4><i class="fa fa-map-marker" aria-hidden="true"></i>Location</h4>
					<p>P. O. Box 10095 (Fed. Sect. B. O.),</p>
					<p>Port Harcourt, River, NIGERIA.</p>
				</div>
				<div class="phone">
					<h4><i class="fa fa-phone" aria-hidden="true"></i>PHONE</h4>
					<p>+234-805-518-4330</p>
					<p>+234-806-794-1410</p>
				</div>
				<div class="email">
					<h4><i class="fa fa-envelope-o" aria-hidden="true"></i>E-MAIL</h4>
					<p><a href="info@mindfoodpubs.com">info@mindfoodpubs.com</a></p>
					<p><a href="admin@mindfoodpubs.com">admin@mindfoodpubs.com</a></p>
					<p><a href="support@mindfoodpubs.com">support@mindfoodpubs.com</a></p>
					<p><a href="emmachima1303@gmail.com">emmachima1303@gmail.com</a></p>
				</div>
                <div class="phone">
					<h4><i class="fa fa-facebook" aria-hidden="true"></i>FACEBOOK</h4>
					<p><a href="facebook.com/Emma Chima
Emma Chima Mind Food Publications
">Emma Chima
Emma Chima Mind Food Publications
</a></p><hr>
					<p><a href="facebook.com/Wisdom TALK">Wisdom TALK</a></p><hr>
                    <p><a href="facebook.com/A Sure Life Foundation">A Sure Life Foundation</a>
				</div>
			</div>
			<div class="col-md-9 col-sm-9 contact-right">
			    
			<?php
				//check for any errors
				if(isset($error)){
					foreach($error as $error){
						echo '<p class="bg-danger">'.$error.'</p>';
					}
				}

				//if action is joined show sucess
				if(isset($_GET['action']) && $_GET['action'] == 'sent'){
					echo "<h2 class='bg-success'>Thanks for contacting Us, Message sent successfully, we'll get back to you soon</h2>";
				}
				?>
			
				<form action="" method="post">
					<input type="text" name="name" placeholder="Your name" required>
					<input type="email" name="email" placeholder="Your email" required>
					<input type="text" name="subject" placeholder="Your subject" required>
					<input type="text" name="phone" placeholder="Phone number" required>
					<textarea name="message" placeholder="Your message" required></textarea>
					<input type="submit" name="submit" value="Send">
				</form>
			</div>
		</div>
	</div>
	<div class="map-w3ls">
		<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d50441.48228771827!2d6.998525081409938!3d4.824330830422525!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sP.+O.+Box+10095+(Fed.+Sect.+B.+O.)%2C+Port+Harcourt%2C+River%2C+NIGERIA!5e1!3m2!1sen!2sng!4v1534640726966" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>



<?php
	require_once("partials/footer.php");
?>

**Comment by zazasco** [comment]
please any review.?

**Comment by daveismyname** [comment]
For general support like this please use my Slack channel https://daveismynameblog.slack.com/join/shared_invite/enQtMzA2MjU4NjExNTU4LThlMTVkY2M2ZTE0MmUzZjk1MDY5N2E3MjQ0NTY2ZmQzOGVhZTgyN2M5NzIyMzk5M2ZlN2VjYmRiYjM2MGM4NDg

This issue isn't directly related to this repo.
