### ISSUE TITLE
Class 'User' not found in config.php

### ISSUE THREAD

**Issue by madmax9922** [daveismyname/loginregister#5]
hi, i got this error when i put the code online. everything works weel localy and i don't know what to do wtih this error.
Class 'User' not found in D:\Hosting\12067690\html\enregistrement\includes\config.php on line 32
this is the line 32: $user = new User($db); 
i'd double check the path and it look like ok.
How i can fix this! Please.
Thx in advance

**Comment by daveismyname** [comment]
you may have an older version make sure the file is being included like this:

````
include('classes/user.php');
````
