### ISSUE TITLE
POST data in input fields in index.php is not escaped

### ISSUE THREAD

**Issue by Martinch0** [daveismyname/loginregister#7]
In index.php the following code snippet is a potential Cross-side scripting hole:

`<input type="text" name="username" id="username" class="form-control input-lg" placeholder="User Name" value="<?php if(isset($error)){ echo $_POST['username']; } ?>" tabindex="1">`

Anyone can fake a POST request to the url and insert arbitrary html/javascript code in the webpage.

Use htmlentities( $_POST['username'] ) to escape the string or do a pattern match on the $_POST['username'] before printing it in the html.

**Comment by daveismyname** [comment]
yes you are correct.
