### ISSUE TITLE
SQLSTATE[HY000] [1045] Access denied for user 'database username'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by darshanparulekar** [daveismyname/loginregister#9]
it show this error message when i open index.php :-SQLSTATE[HY000] [1045] Access denied for user 'database username'@'localhost' (using password: YES)

**Comment by darshanparulekar** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19199238/15035493/1248bb72-12a0-11e6-84f6-a241b2c72279.png)

**Comment by darshanparulekar** [comment]
pls help me!!!!

**Comment by daveismyname** [comment]
it looks like you haven't changed the default database username, password and database name includes/config.php
